# Generated by Django 3.1.7 on 2021-03-12 19:00

from django.db import migrations, models
import django_lifecycle.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPGeolocation',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('ip_address', models.GenericIPAddressField(verbose_name='Ip-Adresse')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('city', models.CharField(blank=True, max_length=511, null=True, verbose_name='Stadt')),
            ],
            options={
                'verbose_name': 'IP-Standort',
                'verbose_name_plural': 'IP-Standorte',
                'ordering': ('city', 'ip_address'),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('token', models.CharField(max_length=6, verbose_name='Token')),
                ('expire_date', models.DateTimeField(verbose_name='Ablaufdatum')),
            ],
            options={
                'verbose_name': 'Einmalpasswort',
                'verbose_name_plural': 'Einmalpasswörter',
                'ordering': ('expire_date',),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
