version: "3.7"

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
      - ./prod.env
    depends_on:
      - db
  db:
    image: postgres
    env_file:
      - ./prod.env
