version: "3.7"

services:
  web:
    build: ./
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    env_file:
      - .env
      - prod.env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    healthcheck:
      test: [ "CMD-SHELL", 'pg_isready -U "tabool_django_role" -d "tabool_django_database"' ]
      interval: 3s
      timeout: 30s
      retries: 3
    env_file:
      - prod.env
    ports:
      - "5432:5432"
