# Generated by Django 3.1.7 on 2021-03-12 19:00

import apps.django.utils.fields.weekday
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.CharField(editable=False, help_text='An unique ID for the object', max_length=127, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Beginn des Schuljahres')),
                ('end_date', models.DateField(verbose_name='Ende des Schuljahres')),
                ('name', models.CharField(max_length=31, unique=True, verbose_name='Bezeichnung')),
            ],
            options={
                'verbose_name': 'Stundenplan',
                'verbose_name_plural': 'Stundenpläne',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.CharField(editable=False, help_text='An unique ID for the object', max_length=127, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('weekday', apps.django.utils.fields.weekday.WeekdayField(choices=[(0, 'Montag'), (1, 'Dienstag'), (2, 'Mittwoch'), (3, 'Donnerstag'), (4, 'Freitag'), (5, 'Samstag'), (6, 'Sonntag')], verbose_name='Wochentag')),
                ('start_hour', models.PositiveSmallIntegerField(verbose_name='Anfangsstunde')),
                ('end_hour', models.PositiveSmallIntegerField(verbose_name='Endstunde')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='Kurs')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.timetable', verbose_name='Stundenplan')),
            ],
            options={
                'verbose_name': 'Stunde',
                'verbose_name_plural': 'Stunden',
                'ordering': ('weekday', 'start_hour', 'end_hour'),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
