# Generated by Django 3.1.7 on 2021-03-12 19:28

import apps.django.utils.fields.color
import apps.django.utils.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_common_utils.libraries.handlers.models
import django_lifecycle.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(editable=False, help_text='An unique ID for the object', max_length=127, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('place', models.CharField(max_length=63, unique=True, validators=[apps.django.utils.validators.validate_place], verbose_name='Ort')),
            ],
            options={
                'verbose_name': 'Raum',
                'verbose_name_plural': 'Räume',
                'ordering': ('place',),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.CharField(editable=False, help_text='An unique ID for the object', max_length=127, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Name')),
                ('short_name', models.CharField(max_length=15, verbose_name='Kurzer Name')),
            ],
            options={
                'verbose_name': 'Fach',
                'verbose_name_plural': 'Fächer',
                'ordering': ('name',),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model, django_common_utils.libraries.handlers.models.HandlerMixin),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.CharField(editable=False, help_text='An unique ID for the object', max_length=127, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=770, null=True, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=770, verbose_name='Letzter Name')),
                ('short_name', models.CharField(blank=True, max_length=3, null=True, verbose_name='Kürzel')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail')),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, 'Männlich'), (1, 'Weiblich'), (2, 'Divers'), (3, 'Unbekannt')], default=3, verbose_name='Geschlecht')),
            ],
            options={
                'verbose_name': 'Lehrer',
                'verbose_name_plural': 'Lehrer',
                'ordering': ('last_name', 'first_name', 'short_name', 'email'),
            },
            bases=(models.Model, django_common_utils.libraries.handlers.models.HandlerMixin),
        ),
        migrations.CreateModel(
            name='TeacherScoosoData',
            fields=[
                ('id', models.CharField(editable=False, help_text='An unique ID for the object', max_length=127, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('scooso_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Scooso-ID')),
                ('code', models.CharField(blank=True, max_length=127, null=True, verbose_name='Lehrer-Code')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school_data.teacher', verbose_name='Lehrer')),
            ],
            options={
                'verbose_name': 'Lehrer-Scooso-Daten',
                'verbose_name_plural': 'Lehrer-Scooso-Daten',
                'ordering': ('code', 'scooso_id'),
            },
        ),
        migrations.CreateModel(
            name='SubjectScoosoData',
            fields=[
                ('id', models.CharField(editable=False, help_text='An unique ID for the object', max_length=127, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('scooso_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Scooso-ID')),
                ('code', models.CharField(blank=True, max_length=127, null=True, verbose_name='Fach-Code')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school_data.subject', verbose_name='Fach')),
            ],
            options={
                'verbose_name': 'Fach-Scooso-Daten',
                'verbose_name_plural': 'Fach-Scooso-Daten',
                'ordering': ('code', 'scooso_id'),
            },
        ),
        migrations.CreateModel(
            name='RoomScoosoData',
            fields=[
                ('id', models.CharField(editable=False, help_text='An unique ID for the object', max_length=127, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('scooso_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Scooso-ID')),
                ('code', models.CharField(blank=True, max_length=31, null=True, verbose_name='Raum-Code')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school_data.room', verbose_name='Raum')),
            ],
            options={
                'verbose_name': 'Raum-Scooso-Daten',
                'verbose_name_plural': 'Raum-Scooso-Daten',
                'ordering': ('code', 'scooso_id'),
            },
        ),
        migrations.CreateModel(
            name='UserSubjectRelation',
            fields=[
                ('id', models.CharField(editable=False, help_text='An unique ID for the object', max_length=127, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('color', apps.django.utils.fields.color.ColorField(blank=True, max_length=11, null=True, verbose_name='Farbe')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_data.subject', verbose_name='Fach')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Fach-Benutzer-Beziehung',
                'verbose_name_plural': 'Fach-Benutzer-Beziehungen',
                'ordering': ('subject', 'user'),
                'unique_together': {('subject', 'user')},
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
