$.extend(scStr, {
    ttb: "Zeiten",
    ttbAddEvent: "Veranstaltung hinzufügen",
    ttbAllday: "Ganztägig",
    ttbAllFiles: "Alle",
    ttbAuthorizationExceeded: "Die Entschuldigungszeit von %d Tagen wurde überschritten. Soll die/der Schülerin/Schüler trotzdem entschuldigt werden?",
    ttbCalendar: "Kalender",
    ttbChangesHeader: "Vertretungsplan",
    ttbDeleteEvent: "Veranstaltung löschen",
    ttbDeleteEventConfirm: "Möchten Sie diese Veranstaltung wirklich löschen?",
    ttbDoScaling: "Skalierung festlegen",
    ttbMsgClassLacks: "Klasse fehlt",
    ttbMsgRoomChange: "Raumänderung",
    ttbMsgCanceled: "fällt aus",
    ttbEndTime: "Ende",
    ttbEndTimePh: "Uhrzeit",
    ttbEventDetails: "Termindetails",
    ttbEventType: "Art",
    ttbEventTypes: {
        1: "Veranstaltung",
        90: "Eigene Fehlzeiten",
        100: "Stundenplan",
        110: "Zusätzlicher Unterricht",
        200: "Aufsicht",
        1010: "Vertretung",
        1020: "Raumänderung",
        1021: "Raum nicht verfügbar",
        1030: "Vertretung eigener Fehlzeiten",
        1040: "Änderung",
        1050: "Fällt aus",
        1060: "Selbstorganisiertes Lernen"
    },
    ttbHomeworkGivenAt: "vom: %s",
    ttbHomeworkTodoUntil: "bis: %s",
    ttbInformation: "Informationen",
    ttbLastScheduleUpdate: "Stand:",
    ttbLocation: "Raum",
    ttbMovedTo: "Verschoben auf",
    ttbMovedFrom: "Verschoben von",
    ttbMyEvents: "Ereignisse",
    ttbMyEventTypeMsg: {
        100: "Deine eingereichte Hausaufgabe vom %s wurde bearbeitet."
    },
    ttbName: "Name",
    ttbNewEvent: "Neue Veranstaltung",
    ttbNewLocation: "Neuer Raum",
    ttbNewSubject: "Neues Fach",
    ttbNewTeacher: "Vertretende Lehrkraft",
    ttbNoEntries: "Keine Einträge",
    ttbOldLocation: "Ursprünglicher Raum",
    ttbOldSubject: "Ursprüngliches Fach",
    ttbOldTeacher: "Fehlende Lehrkraft",
    ttbParticipants: "Lerngruppe(n)",
    ttbSelectCalendar: "Kalenderauswahl",
    ttbActivateCalendars: "Videokonferenzen einblenden",
    ttbStartTime: "Beginn",
    ttbStartDate: "Datum",
    ttbStartTimePh: "Uhrzeit",
    ttbScaling: "Skalierung",
    ttbUnauthorizedStudentOutages: "Unentschuldigte Fehlstunden",
    ttbSubject: "Fach",
    ttbTeacher: "Lehrkraft",
    ttbTitle: "Titel",
    ttbTodoList: "Aufgabenheft",
    ttbTotal: "Total",
    ttbEventUploads: "Upload-Übersicht",
    ttbWeekday: "Wochentag"
});