# Generated by Django 3.1.7 on 2021-03-12 19:00

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timetable', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(editable=False, help_text='An unique ID for the object', max_length=127, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('title', models.CharField(max_length=31, verbose_name='Titel')),
                ('information', models.CharField(blank=True, max_length=1023, null=True, verbose_name='Informationen')),
                ('start_datetime', models.DateTimeField(verbose_name='Start')),
                ('end_datetime', models.DateTimeField(verbose_name='Ende')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ('start_datetime', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.CharField(editable=False, help_text='An unique ID for the object', max_length=127, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False, help_text='Date and time when this was created', max_length=127, verbose_name='Creation date')),
                ('date', models.DateField(help_text='Datum, wann die Klassenarbeit geschrieben wird.', verbose_name='Datum')),
                ('title', models.CharField(max_length=31, verbose_name='Titel')),
                ('information', models.TextField(max_length=1023, verbose_name='Informationen')),
            ],
            options={
                'verbose_name': 'Klausur',
                'verbose_name_plural': 'Klausuren',
                'ordering': ('title', 'date'),
            },
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.CharField(editable=False, help_text='An unique ID for the object', max_length=127, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False, help_text='Date and time when this was created', max_length=127, verbose_name='Creation date')),
                ('lesson_date', models.DateField(verbose_name='Datum')),
                ('information', models.TextField(blank=True, max_length=1023, null=True, verbose_name='Information')),
                ('modification_type', models.CharField(choices=[('REPLACEMENT', 'Vertretung'), ('FREE_PERIOD', 'Freistunde'), ('SELF_LEARN', 'Selbstorganisiertes Lernen'), ('ROOM_CHANGE', 'Raumänderung')], default='REPLACEMENT', help_text='Art von Veränderung', max_length=11, verbose_name='Typ')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.lesson', verbose_name='Stunde')),
                ('new_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.room', verbose_name='Raum')),
                ('new_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.subject', verbose_name='Fach')),
            ],
            options={
                'verbose_name': 'Veränderung',
                'verbose_name_plural': 'Veränderungen',
                'ordering': ('lesson_date', 'lesson__start_hour'),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
