# Generated by Django 3.1.7 on 2021-03-12 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('event', '0001_initial'),
        ('course', '0002_auto_20210312_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='modification',
            name='new_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.teacher', verbose_name='Lehrer'),
        ),
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='Kurs'),
        ),
        migrations.AddField(
            model_name='event',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.room', verbose_name='Raum'),
        ),
    ]
