from django.utils.translation import gettext_lazy as _

from apps.django.utils.translations import *

__all__ = [
    "ROOM", "ROOM_PLURAL", "SUBJECT", "SUBJECT_PLURAL", "TEACHER", "TEACHER_PLURAL", "ROOM_SCOOSO",
    "ROOM_SCOOSO_PLURAL", "SUBJECT_SCOOSO", "SUBJECT_SCOOSO_PLURAL", "TEACHER_SCOOSO", "TEACHER_SCOOSO_PLURAL",
    "SUBJECT_RELATION", "SUBJECT_RELATION_PLURAL"
]

ROOM = _("Raum")
ROOM_PLURAL = _("Räume")

SUBJECT = _("Fach")
SUBJECT_PLURAL = _("Fächer")

TEACHER = TEACHER_PLURAL = _("Lehrer")

ROOM_SCOOSO, ROOM_SCOOSO_PLURAL = scooso_data(ROOM)

SUBJECT_SCOOSO, SUBJECT_SCOOSO_PLURAL = scooso_data(SUBJECT)

TEACHER_SCOOSO, TEACHER_SCOOSO_PLURAL = scooso_data(TEACHER)

SUBJECT_RELATION, SUBJECT_RELATION_PLURAL = user_relation(SUBJECT)
