from apps.event.models.modification import *
from .course import *
from .lesson import *
from .lesson_data import *
from .room import *
from .scooso_data import *
from .subject import *
from .teacher import *
from .user_relations import *
