# Generated by Django 3.1.7 on 2021-03-12 19:00

from django.db import migrations, models
import django_bleach.models
import django_common_utils.libraries.handlers.models
import django_lifecycle.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.CharField(editable=False, help_text='An unique ID for the object', max_length=127, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False, help_text='Date and time when this was created', max_length=127, verbose_name='Creation date')),
                ('edited_at', models.DateTimeField(blank=True, editable=False, help_text='Last date and time when this was edited', max_length=127, null=True, verbose_name='Edit date')),
                ('title', models.CharField(max_length=127, verbose_name='Titel')),
                ('html', django_bleach.models.BleachField(verbose_name='HTML')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ('-created_at', '-edited_at', 'title'),
            },
            bases=(django_common_utils.libraries.handlers.models.HandlerMixin, django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
