# Generated by Django 3.1.7 on 2021-03-12 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_common_utils.libraries.handlers.models
import django_lifecycle.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(editable=False, help_text='An unique ID for the object', max_length=127, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('course_number', models.PositiveSmallIntegerField(default=1, verbose_name='Kursnummer')),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Teilnehmer')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_data.subject', verbose_name='Fach')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_data.teacher', verbose_name='Lehrer')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurse',
                'ordering': ('subject', 'teacher', 'course_number'),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.CharField(editable=False, help_text='An unique ID for the object', max_length=127, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('video_conference_link', models.URLField(blank=True, max_length=1023, null=True, verbose_name='Videokonferenz-Link')),
                ('start_time', models.TimeField(verbose_name='Startzeit')),
                ('end_time', models.TimeField(verbose_name='Endzeit')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.course', verbose_name='Kurs')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_data.room', verbose_name='Raum')),
            ],
            options={
                'verbose_name': 'Stunde',
                'verbose_name_plural': 'Stunden',
                'ordering': ('date', 'start_time', 'end_time'),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LessonScoosoData',
            fields=[
                ('id', models.CharField(editable=False, help_text='An unique ID for the object', max_length=127, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('time_id', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Time-ID')),
                ('lesson_type', models.UUIDField(blank=True, null=True, verbose_name='Stundentyp')),
                ('lesson', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson', verbose_name='Stunde')),
            ],
            options={
                'verbose_name': 'Stunde-Scooso-Daten',
                'verbose_name_plural': 'Stunde-Scooso-Daten',
                'ordering': ('lesson', 'time_id'),
            },
        ),
        migrations.CreateModel(
            name='Classbook',
            fields=[
                ('id', models.CharField(editable=False, help_text='An unique ID for the object', max_length=127, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('presence_content', models.TextField(null=True, verbose_name='Inhalt Präsenzunterricht')),
                ('distance_content', models.TextField(null=True, verbose_name='Inhalt Fernunterricht')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson', verbose_name='Stunde')),
            ],
            options={
                'verbose_name': 'Klassenbuch',
                'verbose_name_plural': 'Klassenbücher',
                'ordering': ('lesson',),
            },
            bases=(models.Model, django_common_utils.libraries.handlers.models.HandlerMixin),
        ),
        migrations.CreateModel(
            name='LessonAbsence',
            fields=[
                ('id', models.CharField(editable=False, help_text='An unique ID for the object', max_length=127, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=63, null=True, verbose_name='Grund')),
                ('is_signed', models.BooleanField(default=False, verbose_name='Ist unterschrieben?')),
                ('associated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson', verbose_name='lesson.Lesson')),
            ],
            options={
                'verbose_name': 'Fehlstunde',
                'verbose_name_plural': 'Fehlstunden',
                'ordering': ('lesson__date', 'lesson__start_time'),
                'unique_together': {('lesson', 'associated_user')},
            },
            bases=(models.Model, django_common_utils.libraries.handlers.models.HandlerMixin),
        ),
    ]
