# Generated by Django 3.1.7 on 2021-03-18 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scooso_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoosorequest',
            options={'verbose_name': 'Scooso-Anfrage', 'verbose_name_plural': 'Scooso-Anfragen'},
        ),
    ]
