# Generated by Django 3.1.7 on 2021-03-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooso_scraper', '0002_auto_20210318_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoosorequest',
            name='response',
            field=models.CharField(max_length=131071),
        ),
    ]
