# Generated by Django 3.1.7 on 2021-03-21 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scooso_scraper', '0003_auto_20210318_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoosorequest',
            options={'ordering': ('created_at',), 'verbose_name': 'Scooso-Anfrage', 'verbose_name_plural': 'Scooso-Anfragen'},
        ),
    ]
