# Generated by Django 3.1.7 on 2021-03-23 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scooso_scraper', '0005_auto_20210323_0928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoosorequest',
            options={'ordering': ('-created_at',), 'verbose_name': 'Scooso-Anfrage', 'verbose_name_plural': 'Scooso-Anfragen'},
        ),
    ]
