# Generated by Django 3.1.7 on 2021-03-12 19:00

import apps.django.utils.fields.color
from django.db import migrations, models
import django_lifecycle.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.CharField(editable=False, help_text='An unique ID for the object', max_length=127, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('text', models.CharField(max_length=24, verbose_name='Text')),
                ('color', apps.django.utils.fields.color.ColorField(blank=True, max_length=11, verbose_name='Farbe')),
            ],
            options={
                'verbose_name': 'Auswahl',
                'verbose_name_plural': 'Auswahlen',
                'ordering': ('text',),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.CharField(editable=False, help_text='An unique ID for the object', max_length=127, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False, help_text='Date and time when this was created', max_length=127, verbose_name='Creation date')),
                ('title', models.CharField(max_length=63, verbose_name='Titel')),
                ('max_vote_date', models.DateTimeField(blank=True, null=True, verbose_name='Maximal Datum zum Abstimmen')),
                ('show_results_date', models.DateTimeField(blank=True, help_text='Ab wann man die Ergebnisse schauen kann', null=True, verbose_name='Veröffentlichkeitsdatum der Ergebnisse')),
                ('min_vote_choices', models.PositiveSmallIntegerField(default=1, help_text='Wie viele Elemente mindestens ausgewählt werden', verbose_name='Mindestanzahl von Auswahlen')),
                ('max_vote_choices', models.PositiveSmallIntegerField(default=1, help_text='Wie viele Elemente maximal ausgewählt werden können', verbose_name='Maximale Abstimmmöglichkeiten')),
            ],
            options={
                'verbose_name': 'Umfrage',
                'verbose_name_plural': 'Umfragen',
                'ordering': ('title', 'created_at'),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.CharField(editable=False, help_text='An unique ID for the object', max_length=127, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False, help_text='Date and time when this was created', max_length=127, verbose_name='Creation date')),
                ('feedback', models.TextField(blank=True, max_length=1023, null=True, verbose_name='Feedback')),
            ],
            options={
                'verbose_name': 'Abstimmung',
                'verbose_name_plural': 'Abstimmungen',
            },
        ),
    ]
