# Generated by Django 3.1.7 on 2021-03-12 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionRelation',
            fields=[
                ('id', models.CharField(editable=False, help_text='An unique ID for the object', max_length=127, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_sessions.session')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
