# Generated by Django 3.1.7 on 2021-03-12 19:05
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
    ]
    
    operations = [
        UnaccentExtension(),
        TrigramExtension()
    ]
