name: Django CI/CD Workflow

on:
  push:
    branches:
      - "**"

jobs:
  healt-check-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache dependency
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

    # Python
      - name: Setup python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Check Python version
        run: python --version
      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Security check
        run: bandit -r ./backend --configfile ./backend/bandit.yaml

    # Django
      - name: Run Makemigrations
        run: python backend/manage.py makemigrations
      - name: Run Migrations
        run: python backend/manage.py migrate
      - name: Run Test
        run: python backend/manage.py test ./backend/ --noinput